name: Docs
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sphinx:
    runs-on: ubuntu-latest
    name: "Sphinx"
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Install system dependencies
        run: >-
          sudo apt-get install -y
          python3-enchant
          aspell-en
          hunspell-en-us
        working-directory: .

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -e .[docs]
        working-directory: .

      - run: sphinx-build -W -b linkcheck -d _build/doctrees . _build/linkcheck
      - run: sphinx-build -W -b spelling -d _build/doctrees . _build/spelling
      - run: sphinx-build -W -b html -d _build/doctrees . _build/html
